### ISSUE TITLE
Inconsistent markup for `\edef` and `\xdef` syntax

### ISSUE THREAD

**Issue by muzimuzhi** [olsak/tex-nutshell#3]
On page 11, _TeX in a Nutshell_ v0.9, the syntax for `\edef` and `\xdef` are colored differently than `\def` and `\gdef`.

![image](https://github.com/olsak/tex-nutshell/assets/6376638/edec3c82-bbf7-445f-a152-795a1f9eae27)

https://github.com/olsak/tex-nutshell/blob/2ae3c848c1706c272ff1bcc90b17d85bd75abf7c/tex-nutshell/tex-nutshell.tex#L868-L873

It seems it's cause by wrong position of `;` in the markup `|...;`.
```patch
From 0bd3c99428624a2f7da17d28eb286aa800b1cc23 Mon Sep 17 00:00:00 2001
From: Yukai Chou <muzimuzhi@gmail.com>
Date: Sun, 28 May 2023 05:37:09 +0800
Subject: [PATCH] Fix markup for \edef and \xdef syntax

---
 tex-nutshell/tex-nutshell.tex | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/tex-nutshell/tex-nutshell.tex b/tex-nutshell/tex-nutshell.tex
index e3f63ed..386a2d4 100644
--- a/tex-nutshell/tex-nutshell.tex
+++ b/tex-nutshell/tex-nutshell.tex
@@ -868,8 +868,8 @@ expanded by the expand processor. The summary of `\def` syntax is:
 \begtt \catcode`\|=13 \catcode`\/=13 \catcode`\<=13 \Blue 
 \def|<control sequence>/<parameters>.{<replacement text>};  % local assignment
 \gdef|<control sequence>/<parameters>.{<replacement text>}; % global assignment
-\edef|<control sequence>/<parameters>.{;<replacement text>} % local assignment
-\xdef|<control sequence>/<parameters>.{;<replacement text>} % global assignment
+\edef|<control sequence>/<parameters>.{<replacement text>}; % local assignment
+\xdef|<control sequence>/<parameters>.{<replacement text>}; % global assignment
 \endtt   
 
 If you set \i tracingmacros `\tracingmacros=2`, you can see in the log file how the macros are expanded.
-- 
2.40.1
```

**Comment by olsak** [comment]
The `<replacement text>` is blue in `\edef` and `\xdef` syntax because these primitives read it fully expanded. On the other hand, the `<replacement text>` is red in `\def` and `\gdef`  syntax because these primitives read it not expanded.

**Comment by muzimuzhi** [comment]
Oh. Then the blue `}` is also intended?

**Comment by olsak** [comment]
Yes, it is blue. Try this:

```
\def\fin{\iffalse{\fi}}

\edef\a{text\fin

\meaning\a
```
The expand processor is normally working when the `<parametere text>` is read including closing `}`.

**Comment by muzimuzhi** [comment]
Ah the brace hack! Thank you I learnt sth new today.

This also explains why the left braces in syntax for `\detokenize`, `\scantokens`, etc., are blue. "TeX performs expansion to find the opening brace of a `<general text>`."
